name: Dependency

options:
  bundleIdPrefix: dev.jano.dependency
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  createIntermediateGroups: true
  deploymentTarget:
    iOS: 15.4

settings:
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES

targets:

  Dependency:
    type: framework
    platform: iOS
    scheme:
      testTargets:
         - DependencyTests
    settings:
       CURRENT_PROJECT_VERSION: 1
       INFOPLIST_FILE: targets/main/Info.plist
       IPHONEOS_DEPLOYMENT_TARGET: 15.4
       PRODUCT_BUNDLE_IDENTIFIER: dev.jano.dependency
       PRODUCT_NAME: Dependency
    sources: 
       - sources/main
    type: framework

  DependencyTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      INFOPLIST_FILE: targets/tests/Info.plist
      IPHONEOS_DEPLOYMENT_TARGET: 15.4
      PRODUCT_BUNDLE_IDENTIFIER: dev.jano.dependency.tests
      TEST_HOST:
    sources:
      - sources/tests
    dependencies:
      - target: Dependency
